# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    - go mod tidy

builds:
  - binary: gpio-fan-control
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X go-gpio-fan-control/pkg/util/version.Version={{.Version}} -X go-gpio-fan-control/pkg/util/version.Branch={{.Branch}} -X go-gpio-fan-control/pkg/util/version.CommitHash={{.Commit}} -X go-gpio-fan-control/pkg/util/version.BuildTimestamp={{.Date}} -X go-gpio-fan-control/pkg/util/version.BuiltBy=goreleaser

nfpms:
  - id: default
    package_name: gpio-fan-control
    vendor: Alyseo
    maintainer: Alyseo Open Source Software <oss@alyseo.com>
    description: A simple fan control using gpio and sysfs file for temperature
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: ./init/gpio-fan-control.service
        dst: /lib/systemd/system/gpio-fan-control.service
        type: config
      - src: ./configs/gpio-fan-control.conf.yml
        dst: /etc/gpio-fan-control/gpio-fan-control.conf.yml
        type: "config|noreplace"
    scripts:
      postinstall: ./deb/postinst
      postremove: ./deb/postrem
    deb:
      scripts:
        templates: ./deb/templates


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
